FROM python:3.7.6
COPY . /opt/pms3003
WORKDIR /opt/pms3003
RUN pip install -r requirements.txt
EXPOSE 8000
ENV AWS_ACCESS_KEY_ID ''
ENV AWS_SECRET_ACCESS_KEY ''
ENV AWS_REGION ''
ENV DYNAMODB_TABLE 'pms3003'
ENV DT_FILTER 21
CMD ["gunicorn", "-b", "0.0.0.0:8000", "wsgi_docker:server"]